export const pakistanData = {
  Punjab: [
    "Lahore",
    "Rawalpindi",
    "Faisalabad",
    "Multan",
    "Gujranwala",
    "Bahawalpur",
    "Sargodha",
    "Sialkot",
    "Gujrat",
    "Jhelum",
    "Sheikhupura",
    "Layyah",
    "Rahim Yar Khan",
    "Sahiwal",
    "Attock",
    "Bhakkar",
    "Chakwal",
    "Chiniot",
    "Dera Ghazi Khan",
    "Hafizabad",
    "Jhang",
    "Kasur",
    "Khanewal",
    "Khushab",
    "Mandi Bahauddin",
    "Mianwali",
    "Nankana Sahib",
    "Narowal",
    "Okara",
    "Pakpattan",
    "Rajanpur",
    "Toba Tek Singh",
    "Vehari",
  ],
  Sindh: [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Mirpur Khas",
    "Jacobabad",
    "Shikarpur",
    "Khairpur",
    "Dadu",
    "Tando Adam",
    "Badin",
    "Thatta",
    "Matiari",
    "Ghotki",
    "Kamber Shahdadkot",
    "Kashmore",
    "Qambar Shahdadkot",
    "Jamshoro",
    "Umerkot",
    "Sanghar",
    "Tharparkar",
    "Sujawal",
    "Tando Allahyar",
    "Tando Muhammad Khan",
  ],
  KhyberPakhtunkhwa: [
    "Peshawar",
    "Abbottabad",
    "Mardan",
    "Kohat",
    "Bannu",
    "Swabi",
    "Mansehra",
    "Nowshera",
    "Charsadda",
    "Dera Ismail Khan",
    "Chitral",
    "Hangu",
    "Haripur",
    "Karak",
    "Kohistan",
    "Lakki Marwat",
    "Lower Dir",
    "Malakand",
    "Swat",
    "Tank",
    "Upper Dir",
  ],
  Balochistan: [
    "Quetta",
    "Gwadar",
    "Khuzdar",
    "Loralai",
    "Lasbela",
    "Mastung",
    "Nushki",
    "Kalat",
    "Kharan",
    "Makran",
    "Chagai",
    "Jaffarabad",
    "Sibi",
    "Zhob",
    "Dera Bugti",
    "Kohlu",
    "Pishin",
    "Barkhan",
    "Washuk",
    "Awaran",
    "Musakhel",
    "Panjgur",
    "Sherani",
  ],
  GilgitBaltistan: [
    "Gilgit",
    "Skardu",
    "Astore",
    "Diamer",
    "Ghanche",
    "Ghizer",
    "Hunza-Nagar",
    "Kharmang",
    "Shigar",
  ],
  AzadKashmir: [
    "Muzaffarabad",
    "Mirpur",
    "Kotli",
    "Bhimber",
    "Hattian",
    "Haveli",
    "Neelam",
    "Poonch",
    "Sudhanoti",
  ],
};
